services:
    nginx:
      build:
          context: docker/nginx
      ports:
          - "8080:8080"
      volumes:
          - ./:/app
      depends_on:
          - php-fpm
    php-fpm:
      build:
          context: docker
          dockerfile: php-fpm/Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
          - ./:/app
      environment:
          APP_DEBUG: 1
          SITE_URL: http://localhost:8080
          SITE_NAME: Docker
          LINK_ANSWERS: http://localhost/answers
          APP_ENV: dev
          DB_HOST: mysql
          DB_USER: app
          DB_PASSWORD: secret
          DB_NAME: app
          MAILER_HOST: mailer
          MAILER_PORT: 1025
          MAILER_USER: app
          MAILER_PASSWORD: secret
          MAILER_ENCRYPTION: tcp
          MAILER_FROM_EMAIL: admin@site.ru
          MAILER_FROM_NAME: admin
          YOOKASSA_SHOP_ID: 221345
          YOOKASSA_SECRET_KEY: test_0B3flJqsbdKNA2sS2dT0ahs74LtF7fwJq2oVR-8wTCM
          YOOKASSA_RETURN_URL: https://localhost/success
          TELEGRAM_BOT_TOKEN: 7239774817:AAEHex3R8hKasS08nahcCJ3WgDfroI2cLBY
          TELEGRAM_CHAT_ID: 1954013093
          AUTH_LOGIN: app
          AUTH_PASSWORD: secret
          MESSENGER_TRANSPORT_DSN: doctrine://default
          UNI_SENDER_API: 6azj4xf5tp7kkkmqi6z1jsqokrse9z5c177tn6de
    php-cli:
      build:
          context: docker
          dockerfile: php-cli/Dockerfile
      volumes:
          - ./:/app
      environment:
          APP_DEBUG: 1
          SITE_URL: http://localhost:8080
          SITE_NAME: Docker
          LINK_ANSWERS: http://localhost/answers
          APP_ENV: dev
          DB_HOST: mysql
          DB_USER: app
          DB_PASSWORD: secret
          DB_NAME: app
          MAILER_HOST: mailer
          MAILER_PORT: 1025
          MAILER_USER: app
          MAILER_PASSWORD: secret
          MAILER_ENCRYPTION: tcp
          MAILER_FROM_EMAIL: admin@site.ru
          MAILER_FROM_NAME: admin
          YOOKASSA_SHOP_ID: 221345
          YOOKASSA_SECRET_KEY: test_0B3flJqsbdKNA2sS2dT0ahs74LtF7fwJq2oVR-8wTCM
          YOOKASSA_RETURN_URL: https://localhost/success
          TELEGRAM_BOT_TOKEN: 8593901883:AAFlIYytEQRRgCDmdoLhAiSPXVfdRU1rffg
          TELEGRAM_CHAT_ID: 1954013093
          AUTH_LOGIN: app
          AUTH_PASSWORD: secret
          MESSENGER_TRANSPORT_DSN: doctrine://default
          UNI_SENDER_API: 6azj4xf5tp7kkkmqi6z1jsqokrse9z5c177tn6de
    mysql:
      image:  mysql:8.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: app
        MYSQL_PASSWORD: secret
        MYSQL_DATABASE: app
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "33061:3306"
      command: --default-authentication-plugin=mysql_native_password

    mailer:
      image: mailhog/mailhog
      ports:
        - "8082:8025"

volumes:
  mysql: