
POST http://localhost/payment-service/process-payment
Content-Type: application/json

{
    "email":"test@app.ru",
    "productId": "b38e76c0-ac23-4c48-85fd-975f32c8801f"
}

###

POST http://localhost/payment-service/payment-webhook
Content-Type: application/json
User-Agent: Yookassa

{
    "type": "notification",
    "event": "payment.succeeded",
    "object": {
        "id": "308648ae-000f-5001-8000-127b00f66a5a",
        "status": "succeeded",
        "paid": true,
        "amount": {
            "value": "450.00",
            "currency": "RUB"
        },
        "income_amount": {
            "value": "435.00",
            "currency": "RUB"
        },
        "recipient": {
            "account_id": "221345",
            "gateway_id": "2093840"
        },
        "created_at": "2025-10-13T05:19:27.347Z",
        "captured_at": "2025-10-13T05:20:00.000Z",
        "metadata": {
            "productId": "b38e76c0-ac23-4c48-85fd-975f32c8801f",
            "cms_name": "yookassa_sdk_php_3",
            "email": "flaaim@list.ru"
        }
    }
}


###

POST http://localhost/payment-service/result
Content-Type: application/json

{
    "returnToken": "392b1c38-f3e4-4533-a6cb-5b4e7c08d91f"
}