name: ci.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache API Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Init
        run: make init

      - name: Lint
        run: make app-lint

      - name: Psalm
        run: make app-psalm

      - name: validate-schema
        run: make validate-schema

      - name: Test
        run: make test

      - name: Archive tests output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: var/log
        if: ${{ always() && steps.Test.outcome == 'failure' }}
